### ISSUE TITLE
Xavier NX Jetpack L4T 32.4.3, which branch should I use?

### ISSUE THREAD

**Issue by shmm91** [alliedvision/linux_nvidia_jetson#15]
As in title, my harware is Jetson Xavier NX, Jetpack is L4T 32.4.3.
Which branch version should I use?

**Comment by BernardoLuck** [comment]
Hello shmm91, 
we do not have a specific driver for the version L4T 32.4.3. However, our driver for the version 32.4.2 should work on 32.4.3, too. Nevertheless, I strongly recommend to use L4T 32.4.4 with our recent driver. 
BR
Bernardo
