### ISSUE TITLE
Where can I download the Xavier kernel

### ISSUE THREAD

**Issue by eli-davis** [alliedvision/linux_nvidia_jetson#21]
I have been using the xavier kernel downloaded from https://www.alliedvision.com/en/products/software/embedded-software-and-drivers/precompiled-kernel.html - Where can I download it from now?

**Comment by BernardoLuck** [comment]
Hi, you can download the precompiled drivers from here: https://github.com/alliedvision/linux_nvidia_jetson/releases/tag/l4t-32.5.1-2.0.0
