### ISSUE TITLE
Jetpack 4.6 support?

### ISSUE THREAD

**Issue by makkarpov** [alliedvision/linux_nvidia_jetson#30]
Jetpack 4.6 is released, is there any ETA on supporting it?

It introduces tons of features that make downgrading to 4.5.1 not feasible.

**Comment by arunprakash-avt** [comment]
Thanks for for writting us, yes we are working on it and sorry to say that we dont have any timeplan for the release for Jetpack 4.6.

**Comment by makkarpov** [comment]
Also, there is one suggestion of publication format.

Currently binaries are published as "blobs", e.g. whole kernel that must be compiled and placed over the default one. This makes merging two changes (e.g. when you want a camera driver and something other) rather hard, because basically expected process from AlliedVision side is to compile and overwrite.

Could you provide diffs with changes? Or, even better (if it possible) distribute the driver as a dynamic kernel module?

**Comment by wittenator** [comment]
Our team is also desperately waiting for the 4.6 release since the updates in the Deepstream 6.0 SDK (which depend on Jetpack 4.6) would make our life and the integration of our AV cameras way easier.

**Comment by beniroquai** [comment]
Same here! Would very much appreciate to see the camera working on the 4.6 release.

**Comment by trekker99** [comment]
yes, this is something my team is waiting for also.

**Comment by unca121** [comment]
same here

**Comment by eliabruni** [comment]
same here!

**Comment by BernardoLuck** [comment]
Hello guys, our R&D team is finalizing the driver for Jetpack 4.6. It will take not longer until we upload a beta version of the driver here.

BR
Bernardo Luck Villanueva // Applications Engineer

Allied Vision Technologies GmbH

**Comment by eliabruni** [comment]
That's great news, looking forward to testing it!
