### ISSUE TITLE
Method A: Use precompiled binaries where is the precompiled tar?

### ISSUE THREAD

**Issue by rebotnix** [alliedvision/linux_nvidia_jetson#37]
We bought several CSI cameras from your company and we are searching for the pre-compiled driver and tar file.

In your README you wrote:
Method A: Use precompiled binaries

Install the precompiled kernel including driver and installation instructions.
For Jetson Nano, please use the file containing "a02" for A02 carrier boards and the other file for B01 carrier boards.

Extract the tarball on a host PC.

The tarball contains helper scripts and another tarball with the precompiled binaries named AlliedVision_NVidia_L4T_32.5.1_.tar.gz.

It would be useful that we know where we can download the AlliedVision_NVidia_L4T_32.5.1_.tar.gz file?

**Comment by AVTechie** [comment]
Find the Releases section on the page and choose latest release (2.1). There you can find the binaries. I hope that helps

**Comment by rebotnix** [comment]
Thank you very much, for all other users, here is the link:
https://github.com/alliedvision/linux_nvidia_jetson/releases

It seems that there is no precompiled NX version, saw in 2.1 release Nano, TX2 and AGX. We try to recompile NX from source and with that.

**Comment by BernardoLuck** [comment]
the compiled version for the NX is same as for the AGX
