### ISSUE TITLE
Error: avt-nvidia-l4t-kernel : Conflicts: nvidia-l4t-kernel but 4.9.253-tegra-32.7.1-20220219090344 is to be installed

### ISSUE THREAD

**Issue by tanvubc** [alliedvision/linux_nvidia_jetson#40]
Hi all,
I am installing csi2 driver for my Jetson TX2 (`Jetpack 4.6.1, l4t-32.7.1`) with release 4.0.0~beta1, and I am facing an error when copy, extract tarball to target device and run command: `sudo ./install.sh`:

```
acanus@ubuntu:~/github/AlliedVision_NVidia_xavier_L4T_32.7.1_4.0.0~beta1$ sudo ./install.sh -y
Allied Vision MIPI CSI-2 camera driver for NVidia Jetson (kernel 4.9.253)
Extracting repository:
Release.gpg
KEY.gpg
Release
Packages
avt-nvidia-l4t-kernel-dtbs_4.9.253-tegra-32.7.1-4.0.0~beta1_arm64.deb
avt-nvidia-l4t-kernel-headers_4.9.253-tegra-32.7.1-4.0.0~beta1_arm64.deb
avt-nvidia-l4t-bootloader_32.7.1-4.0.0~beta1_arm64.deb
avt-nvidia-l4t-kernel_4.9.253-tegra-32.7.1-4.0.0~beta1_arm64.deb
Importing Repository:
OK
deb file:/opt/avt/packages ./
Get:1 file:/opt/avt/packages ./ InRelease
Ign:1 file:/opt/avt/packages ./ InRelease
Get:2 file:/opt/avt/packages ./ Release [816 B]
Get:2 file:/opt/avt/packages ./ Release [816 B]
Get:3 file:/opt/avt/packages ./ Release.gpg [691 B]
Get:3 file:/opt/avt/packages ./ Release.gpg [691 B]
Hit:4 https://repo.download.nvidia.com/jetson/common r32.7 InRelease
Hit:5 https://repo.download.nvidia.com/jetson/t186 r32.7 InRelease
Hit:6 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Hit:7 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Hit:8 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Get:9 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease [88.7 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports bionic-security/main arm64 Packages [1,230 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports bionic-security/main Translation-en [392 kB]
Fetched 1,711 kB in 4s (452 kB/s)
Reading package lists... Done
Installing packages:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 avt-nvidia-l4t-kernel : Conflicts: nvidia-l4t-kernel but 4.9.253-tegra-32.7.1-20220219090344 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Here some info of target device:

> acanus@ubuntu:~$ apt show nvidia-jetpack -a
> Package: nvidia-jetpack
> Version: 4.6.2-b5
> Priority: standard
> Section: metapackages
> Maintainer: NVIDIA Corporation
> Installed-Size: 199 kB
> Depends: nvidia-cuda (= 4.6.2-b5), nvidia-opencv (= 4.6.2-b5), nvidia-cudnn8 (= 4.6.2-b5), nvidia-tensorrt (= 4.6.2-b5), nvidia-visionworks (= 4.6.2-b5), nvidia-container (= 4.6.2-b5), nvidia-vpi (= 4.6.2-b5), nvidia-l4t-jetson-multimedia-api (>> 32.7-0), nvidia-l4t-jetson-multimedia-api (<< 32.8-0)
> Homepage: http://developer.nvidia.com/jetson
> Download-Size: 29.4 kB
> APT-Sources: https://repo.download.nvidia.com/jetson/t186 r32.7/main arm64 Packages
> Description: NVIDIA Jetpack Meta Package
> 
> Package: nvidia-jetpack
> Version: 4.6.1-b110
> Priority: standard
> Section: metapackages
> Maintainer: NVIDIA Corporation
> Installed-Size: 199 kB
> Depends: nvidia-cuda (= 4.6.1-b110), nvidia-opencv (= 4.6.1-b110), nvidia-cudnn8 (= 4.6.1-b110), nvidia-tensorrt (= 4.6.1-b110), nvidia-visionworks (= 4.6.1-b110), nvidia-container (= 4.6.1-b110), nvidia-vpi (= 4.6.1-b110), nvidia-l4t-jetson-multimedia-api (>> 32.7-0), nvidia-l4t-jetson-multimedia-api (<< 32.8-0)
> Homepage: http://developer.nvidia.com/jetson
> Download-Size: 29.4 kB
> APT-Sources: https://repo.download.nvidia.com/jetson/t186 r32.7/main arm64 Packages
> Description: NVIDIA Jetpack Meta Package

Please help me out, thanks in advance.

**Comment by nikitamankovskii** [comment]
Faceing exactly the same issue on new setted device (jetson nx)

**Comment by nikitamankovskii** [comment]
Some more information:
The error menstioned before can be fixed with:
```
sudo apt update
sudo apt upgrade
```
BUT  here next problem appears - wrong dependances version:
```
The following packages have unmet dependencies:
 avt-nvidia-l4t-bootloader : Depends: nvidia-l4t-tools (= 32.7.1-20220219090344) but 32.7.2-20220417024839 is to be installed
```
Looks like its regardiung the update the `Jetpack Version: 4.6.2`, which you are getting with installation on 4.6.1

**Comment by tanvubc** [comment]
> Faceing exactly the same issue on new setted device (jetson nx)

Have you solved your problem?
If not yet, you can follow installation instruction in (https://github.com/alliedvision/linux_nvidia_jetson/tree/l4t-32.7.1/avt_build/jetson_build/installer)/install.sh.
In my case, I just install nvidia-l4t-tools with specified version (= 32.7.1-20220219090344) and install manually ONE BY ONE these packages: avt-nvidia-l4t-bootloader avt-nvidia-l4t-kernel avt-nvidia-l4t-kernel-dtbs avt-nvidia-l4t-kernel-headers (these packages can be found in line 70 of install.sh file. And it works after I reboot my jetson.
Hope this may help you. 

>Looks like its regardiung the update the Jetpack Version: 4.6.2, which you are getting with installation on 4.6.1
I installed jetpack version 4.6.1, I have no idea why my jetson have both jetpack version 4.6.1 and 4.6.2

**Comment by aidanwhelan** [comment]
I'm having the same issue. After a fresh flash of JetPack 4.6.1 using the NVidia SDK Manager, I get:  
```
The following packages have unmet dependencies:
 avt-nvidia-l4t-kernel : Conflicts: nvidia-l4t-kernel but 4.9.253-tegra-32.7.1-20220219090432 is to be installed  
```  
After upgrading with `sudo apt update` and `sudo apt upgrade`, it seems like apt sources the newest debian packages for JetPack 4.6, which upgrades the packages from L4T 32.7.1 to L4T 32.7.2, which causes the same bootloader mismatch that @nikitamankovskii had.   

> In my case, I just install nvidia-l4t-tools with specified version (= 32.7.1-20220219090344) and install manually ONE BY ONE these packages: avt-nvidia-l4t-bootloader avt-nvidia-l4t-kernel avt-nvidia-l4t-kernel-dtbs avt-nvidia-l4t-kernel-headers (these packages can be found in line 70 of install.sh file.

@tanvubc I'm encouraged to hear you found a solution, and I'm eager to understand more about how you did it. Could you explain the steps you took to do these specific installations? How did you set the specific version of nvidia-l4t-tools?

**Comment by tanvubc** [comment]
> I'm having the same issue. After a fresh flash of JetPack 4.6.1 using the NVidia SDK Manager, I get:
> 
> ```
> The following packages have unmet dependencies:
>  avt-nvidia-l4t-kernel : Conflicts: nvidia-l4t-kernel but 4.9.253-tegra-32.7.1-20220219090432 is to be installed  
> ```
> 
> After upgrading with `sudo apt update` and `sudo apt upgrade`, it seems like apt sources the newest debian packages for JetPack 4.6, which upgrades the packages from L4T 32.7.1 to L4T 32.7.2, which causes the same bootloader mismatch that @nikitamankovskii had.
> 
Hi @aidanwhelan, after re-install this driver once again, I realized that the only problem is my jetson has mismatch version of nvidia-l4t-tools. So you can try manually install nvidia-l4t-tools with right version and run command `sudo ./install.sh` again.
> 
> @tanvubc I'm encouraged to hear you found a solution, and I'm eager to understand more about how you did it. Could you explain the steps you took to do these specific installations? How did you set the specific version of nvidia-l4t-tools?

I ran command `sudo apt-get install nvidia-l4t-tools=32.7.1-20220219090344`
