### ISSUE TITLE
Jetson Xavier NX 16-GB LPDDR4 with JetPack 4.5.1

### ISSUE THREAD

**Issue by l4es** [alliedvision/linux_nvidia_jetson#44]
Hi,

Do you support the new Jetson Xavier NX module with 16GB LPDDR4 in JetPack 4.5.1, please ?

Thanks and best regards,
Pascal.

**Comment by Teresa-AlliedVision** [comment]
Hello Pascal,

for the 16GB Jetson Xavier NX 16 GB module, you would need to use at least Jetpack 4.6.1. 
The 3.0.0 driver does not work with the 16 GB version unfortunately.
Have a look under releases, to see the more information on the GenICam over CSI drivers. 

https://github.com/alliedvision/linux_nvidia_jetson/releases

Cheers,
Teresa
