### ISSUE TITLE
Jetpack 5.x support

### ISSUE THREAD

**Issue by r0l1** [alliedvision/linux_nvidia_jetson#48]
Can you please elaborate more about the Jetpack 5.x roadmap? When will it be supported by AlliedVision?

**Comment by AVTechie** [comment]
A beta driver for 5.0.1 is already available in the releases section. Please let us know if you experience any issues with it: https://github.com/alliedvision/linux_nvidia_jetson/releases/tag/l4t-34.1.1-5.0.1-beta-1

**Comment by r0l1** [comment]
Great thanks for the info. I'll give it a shot. Any plans to support the final production ready Jetson release 5.0.2?
