### ISSUE TITLE
Driver Support for 5.0.2 / Jetson Linux 35.1

### ISSUE THREAD

**Issue by ah-gus** [alliedvision/linux_nvidia_jetson#56]
tried to use the precompiled for 5.0.1 , but incompatible
building from sources of 34.X beta   , also - installation failure.
is there a roadmap/date for support?
wev'e been with a technical debt for very long and camera drivers are now our bottleneck

**Comment by harelhel** [comment]
Same issue here - upvote

**Comment by AVTechie** [comment]
We just release a beta for JetPack 5.0.2. Check it out here: https://github.com/alliedvision/linux_nvidia_jetson/releases/tag/l4t-35.1.0-5.0.2-beta1
