### ISSUE TITLE
Error installing driver package on Orin with Jetpack 5.1, L4T 35.2.1

### ISSUE THREAD

**Issue by logicalelegance** [alliedvision/linux_nvidia_jetson#69]
Jetpack version:

Package: nvidia-jetpack
Version: 5.1-b147
Architecture: arm64
Maintainer: NVIDIA Corporation
Installed-Size: 194
Depends: nvidia-jetpack-runtime (= 5.1-b147), nvidia-jetpack-dev (= 5.1-b147)
Homepage: http://developer.nvidia.com/jetson
Priority: standard
Section: metapackages
Filename: pool/main/n/nvidia-jetpack/nvidia-jetpack_5.1-b147_arm64.deb
Size: 29306
SHA256: 750acd147aa354a2dff225245149c8ac6a3802234157f2185c5d1b6fa9b9d2d9
SHA1: 8363c940eadd7300de57a70e2cd99dd321781b1c
MD5sum: 3da9b145351144eb1588e07f04e1e3d3
Description: NVIDIA Jetpack Meta Package
Description-md5: ad1462289bdbc54909ae109d1d32c0a8

L4T Version:

``` # R35 (release), REVISION: 2.1, GCID: 32413640, BOARD: t186ref, EABI: aarch64, DATE: Tue Jan 24 23:38:33 UTC 2023```

I'm installing from the package AlliedVision_NVidia_L4T_35.2.1_5.1.0.gad1411701.tar.gz. 

When installing, the avt-nvidia-l4t-bootloader package fails to configure with this message:

<img width="493" alt="image" src="https://github.com/alliedvision/linux_nvidia_jetson/assets/2035252/51045c3a-226d-4681-90df-4d2334271d05">

Which produces this error in the script:

```
After this operation, 2,711 MB of additional disk space will be used.
Get:1 file:/opt/avt/packages ./ avt-nvidia-l4t-bootloader 35.2.1-5.1.0~gad1411701 [85.7 MB]
Get:2 file:/opt/avt/packages ./ avt-nvidia-l4t-kernel 5.10.104-tegra-35.2.1-5.1.0~gad1411701 [363 MB]
Get:3 file:/opt/avt/packages ./ avt-nvidia-l4t-kernel-dtbs 5.10.104-tegra-35.2.1-5.1.0~gad1411701 [331 kB]
Get:4 file:/opt/avt/packages ./ avt-nvidia-l4t-kernel-headers 5.10.104-tegra-35.2.1-5.1.0~gad1411701 [11.5 MB]
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package avt-nvidia-l4t-bootloader.
(Reading database ... 137824 files and directories currently installed.)
Preparing to unpack .../avt-nvidia-l4t-bootloader_35.2.1-5.1.0~gad1411701_arm64.deb ...
Unpacking avt-nvidia-l4t-bootloader (35.2.1-5.1.0~gad1411701) ...
Selecting previously unselected package avt-nvidia-l4t-kernel.
Preparing to unpack .../avt-nvidia-l4t-kernel_5.10.104-tegra-35.2.1-5.1.0~gad1411701_arm64.deb ...
Unpacking avt-nvidia-l4t-kernel (5.10.104-tegra-35.2.1-5.1.0~gad1411701) ...
Selecting previously unselected package avt-nvidia-l4t-kernel-dtbs.
Preparing to unpack .../avt-nvidia-l4t-kernel-dtbs_5.10.104-tegra-35.2.1-5.1.0~gad1411701_arm64.deb ...
Unpacking avt-nvidia-l4t-kernel-dtbs (5.10.104-tegra-35.2.1-5.1.0~gad1411701) ...
Selecting previously unselected package avt-nvidia-l4t-kernel-headers.
Preparing to unpack .../avt-nvidia-l4t-kernel-headers_5.10.104-tegra-35.2.1-5.1.0~gad1411701_arm64.deb ...
Unpacking avt-nvidia-l4t-kernel-headers (5.10.104-tegra-35.2.1-5.1.0~gad1411701) ...
Setting up avt-nvidia-l4t-kernel (5.10.104-tegra-35.2.1-5.1.0~gad1411701) ...
Setting up avt-nvidia-l4t-kernel-headers (5.10.104-tegra-35.2.1-5.1.0~gad1411701) ...
Setting up avt-nvidia-l4t-bootloader (35.2.1-5.1.0~gad1411701) ...
dpkg: error processing package avt-nvidia-l4t-bootloader (--configure):
 installed avt-nvidia-l4t-bootloader package post-installation script subprocess returned error exit status 1
Setting up avt-nvidia-l4t-kernel-dtbs (5.10.104-tegra-35.2.1-5.1.0~gad1411701) ...
Errors were encountered while processing:
 avt-nvidia-l4t-bootloader
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Not sure what I should try here, update to a newer Jetpack? Thanks.

**Comment by fgrcar** [comment]
I have the same issue on Orin with L4T 35.4.1. Tried both precompiled binaries and building from source. Orin is not even mentioned in the build scripts, only Xavier and Nano but later on Nano is even commented out in code which is weird. 
README file clearly says it should work and their website as well, so I don't know why nobody responds here :thinking:.

**Comment by arunprakash-avt** [comment]
The Jetpack 5.1 is not support by Nvidia for Orin AGX 64GB . Please check the below link, under this topic 
https://docs.nvidia.com/jetson/archives/r35.1/DeveloperGuide/index.html#devices-supported-by-this-document
