### ISSUE TITLE
compatibility with nvarguscamerasrc and Jetson ISP

### ISSUE THREAD

**Issue by haitomatic** [alliedvision/linux_nvidia_jetson#71]
Hi,
I am wondering if the driver is compatible with Nvidia Jetson ISP and nvarguscamerasrc gst plugin?
Or v4l2src is the only way to grab frame from Alvium cameras?
Thanks

**Comment by arunprakash-avt** [comment]
Hi,
As of now it is only possible with V4L2, could be possible when the driver support for Jetpack 6.1 is released.

For further queries please write us an email to support@alliedvision.com
Thanks

**Comment by haitomatic** [comment]
Hi,
Thanks for the reply. I can also check the vimba sdk meanwhile.
BR
Hai To
________________________________
